// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.aurora.grpc;

public interface BatchTelemetryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.BatchTelemetryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 多条指标
   * </pre>
   *
   * <code>repeated .aurora.TelemetryRequest metrics = 1;</code>
   */
  java.util.List<com.aurora.grpc.TelemetryRequest> 
      getMetricsList();
  /**
   * <pre>
   * 多条指标
   * </pre>
   *
   * <code>repeated .aurora.TelemetryRequest metrics = 1;</code>
   */
  com.aurora.grpc.TelemetryRequest getMetrics(int index);
  /**
   * <pre>
   * 多条指标
   * </pre>
   *
   * <code>repeated .aurora.TelemetryRequest metrics = 1;</code>
   */
  int getMetricsCount();
  /**
   * <pre>
   * 多条指标
   * </pre>
   *
   * <code>repeated .aurora.TelemetryRequest metrics = 1;</code>
   */
  java.util.List<? extends com.aurora.grpc.TelemetryRequestOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <pre>
   * 多条指标
   * </pre>
   *
   * <code>repeated .aurora.TelemetryRequest metrics = 1;</code>
   */
  com.aurora.grpc.TelemetryRequestOrBuilder getMetricsOrBuilder(
      int index);
}
