// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public final class MetricProto {
  private MetricProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014metric.proto\022\006aurora\"l\n\rMetricMessage\022" +
      "\017\n\007placeId\030\001 \001(\005\022\n\n\002ip\030\002 \001(\t\022\014\n\004time\030\003 \001" +
      "(\003\022\013\n\003pid\030\004 \001(\005\022#\n\007metrics\030\005 \003(\0132\022.auror" +
      "a.MetricItem\"(\n\nMetricItem\022\013\n\003tid\030\006 \001(\005\022" +
      "\r\n\005value\030\007 \001(\001\"*\n\tMetricAck\022\014\n\004code\030\001 \001(" +
      "\005\022\017\n\007message\030\002 \001(\t2E\n\rMetricService\0224\n\006R" +
      "eport\022\025.aurora.MetricMessage\032\021.aurora.Me" +
      "tricAck(\001B \n\017com.aurora.grpcB\013MetricProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aurora_MetricMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aurora_MetricMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricMessage_descriptor,
        new java.lang.String[] { "PlaceId", "Ip", "Time", "Pid", "Metrics", });
    internal_static_aurora_MetricItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aurora_MetricItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricItem_descriptor,
        new java.lang.String[] { "Tid", "Value", });
    internal_static_aurora_MetricAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aurora_MetricAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricAck_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
