// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: processmetric.proto

package com.aurora.grpc;

public interface ProcessMetricItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.ProcessMetricItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tid = 7;</code>
   * @return The tid.
   */
  int getTid();

  /**
   * <code>double value = 8;</code>
   * @return The value.
   */
  double getValue();
}
