// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.aurora.grpc;

public final class TelemetryProto {
  private TelemetryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_TelemetryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_TelemetryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_TelemetryRequest_TagsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_TelemetryRequest_TagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_BatchTelemetryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_BatchTelemetryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017telemetry.proto\022\006aurora\"\243\001\n\020TelemetryR" +
      "equest\022\016\n\006metric\030\001 \001(\t\022\r\n\005value\030\002 \001(\001\022\021\n" +
      "\ttimestamp\030\003 \001(\003\0220\n\004tags\030\004 \003(\0132\".aurora." +
      "TelemetryRequest.TagsEntry\032+\n\tTagsEntry\022" +
      "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"B\n\025Batch" +
      "TelemetryRequest\022)\n\007metrics\030\001 \003(\0132\030.auro" +
      "ra.TelemetryRequest\"$\n\003Ack\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t2\200\001\n\020TelemetryService\0221" +
      "\n\006Report\022\030.aurora.TelemetryRequest\032\013.aur" +
      "ora.Ack(\001\0229\n\013ReportBatch\022\035.aurora.BatchT" +
      "elemetryRequest\032\013.aurora.AckB#\n\017com.auro" +
      "ra.grpcB\016TelemetryProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aurora_TelemetryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aurora_TelemetryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_TelemetryRequest_descriptor,
        new java.lang.String[] { "Metric", "Value", "Timestamp", "Tags", });
    internal_static_aurora_TelemetryRequest_TagsEntry_descriptor =
      internal_static_aurora_TelemetryRequest_descriptor.getNestedTypes().get(0);
    internal_static_aurora_TelemetryRequest_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_TelemetryRequest_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_aurora_BatchTelemetryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aurora_BatchTelemetryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_BatchTelemetryRequest_descriptor,
        new java.lang.String[] { "Metrics", });
    internal_static_aurora_Ack_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aurora_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_Ack_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
