// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface BatchMetricDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.BatchMetricDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 指标消息列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataMessage metrics = 1;</code>
   */
  java.util.List<com.aurora.grpc.MetricDataMessage> 
      getMetricsList();
  /**
   * <pre>
   * 指标消息列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataMessage metrics = 1;</code>
   */
  com.aurora.grpc.MetricDataMessage getMetrics(int index);
  /**
   * <pre>
   * 指标消息列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataMessage metrics = 1;</code>
   */
  int getMetricsCount();
  /**
   * <pre>
   * 指标消息列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataMessage metrics = 1;</code>
   */
  java.util.List<? extends com.aurora.grpc.MetricDataMessageOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <pre>
   * 指标消息列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataMessage metrics = 1;</code>
   */
  com.aurora.grpc.MetricDataMessageOrBuilder getMetricsOrBuilder(
      int index);
}
