// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.aurora.grpc;

public interface BatchEventDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.BatchEventDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 事件列表
   * </pre>
   *
   * <code>repeated .aurora.EventDataMessage events = 1;</code>
   */
  java.util.List<com.aurora.grpc.EventDataMessage> 
      getEventsList();
  /**
   * <pre>
   * 事件列表
   * </pre>
   *
   * <code>repeated .aurora.EventDataMessage events = 1;</code>
   */
  com.aurora.grpc.EventDataMessage getEvents(int index);
  /**
   * <pre>
   * 事件列表
   * </pre>
   *
   * <code>repeated .aurora.EventDataMessage events = 1;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   * 事件列表
   * </pre>
   *
   * <code>repeated .aurora.EventDataMessage events = 1;</code>
   */
  java.util.List<? extends com.aurora.grpc.EventDataMessageOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   * 事件列表
   * </pre>
   *
   * <code>repeated .aurora.EventDataMessage events = 1;</code>
   */
  com.aurora.grpc.EventDataMessageOrBuilder getEventsOrBuilder(
      int index);
}
