// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicemetric.proto

package com.aurora.grpc;

public interface DeviceMetricMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metric.DeviceMetricMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 placeId = 1;</code>
   * @return The placeId.
   */
  int getPlaceId();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int64 time = 3;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>repeated .metric.DeviceMetricItem metrics = 5;</code>
   */
  java.util.List<com.aurora.grpc.DeviceMetricItem> 
      getMetricsList();
  /**
   * <code>repeated .metric.DeviceMetricItem metrics = 5;</code>
   */
  com.aurora.grpc.DeviceMetricItem getMetrics(int index);
  /**
   * <code>repeated .metric.DeviceMetricItem metrics = 5;</code>
   */
  int getMetricsCount();
  /**
   * <code>repeated .metric.DeviceMetricItem metrics = 5;</code>
   */
  java.util.List<? extends com.aurora.grpc.DeviceMetricItemOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <code>repeated .metric.DeviceMetricItem metrics = 5;</code>
   */
  com.aurora.grpc.DeviceMetricItemOrBuilder getMetricsOrBuilder(
      int index);
}
