// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicemetric.proto

package com.aurora.grpc;

public final class Devicemetric {
  private Devicemetric() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metric_DeviceMetricMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metric_DeviceMetricMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metric_DeviceMetricItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metric_DeviceMetricItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metric_DeviceMetricAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metric_DeviceMetricAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022devicemetric.proto\022\006metric\"k\n\023DeviceMe" +
      "tricMessage\022\017\n\007placeId\030\001 \001(\005\022\n\n\002ip\030\002 \001(\t" +
      "\022\014\n\004time\030\003 \001(\003\022)\n\007metrics\030\005 \003(\0132\030.metric" +
      ".DeviceMetricItem\".\n\020DeviceMetricItem\022\013\n" +
      "\003tid\030\006 \001(\005\022\r\n\005value\030\007 \001(\001\"0\n\017DeviceMetri" +
      "cAck\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2W\n\023D" +
      "eviceMetricService\022@\n\006Report\022\033.metric.De" +
      "viceMetricMessage\032\027.metric.DeviceMetricA" +
      "ck(\001B%\n\017com.aurora.grpcP\001\252\002\017SystemData.G" +
      "rpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_metric_DeviceMetricMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metric_DeviceMetricMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metric_DeviceMetricMessage_descriptor,
        new java.lang.String[] { "PlaceId", "Ip", "Time", "Metrics", });
    internal_static_metric_DeviceMetricItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_metric_DeviceMetricItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metric_DeviceMetricItem_descriptor,
        new java.lang.String[] { "Tid", "Value", });
    internal_static_metric_DeviceMetricAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_metric_DeviceMetricAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metric_DeviceMetricAck_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
