// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicemetric.proto

package com.aurora.grpc;

public interface DeviceMetricItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:metric.DeviceMetricItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tid = 6;</code>
   * @return The tid.
   */
  int getTid();

  /**
   * <code>double value = 7;</code>
   * @return The value.
   */
  double getValue();
}
