// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.aurora.grpc;

public interface EventDataMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.EventDataMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 事件时间戳（Unix 毫秒时间戳）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 事件类型 - 4字节无符号整数，标识事件类型
   * </pre>
   *
   * <code>uint32 eventType = 2;</code>
   * @return The eventType.
   */
  int getEventType();

  /**
   * <pre>
   * 跟踪上下文
   * </pre>
   *
   * <code>bytes traceId = 3;</code>
   * @return The traceId.
   */
  com.google.protobuf.ByteString getTraceId();

  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 4;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 4;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <pre>
   * 事件的数据内容
   * </pre>
   *
   * <code>map&lt;string, string&gt; eventData = 5;</code>
   */
  int getEventDataCount();
  /**
   * <pre>
   * 事件的数据内容
   * </pre>
   *
   * <code>map&lt;string, string&gt; eventData = 5;</code>
   */
  boolean containsEventData(
      java.lang.String key);
  /**
   * Use {@link #getEventDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEventData();
  /**
   * <pre>
   * 事件的数据内容
   * </pre>
   *
   * <code>map&lt;string, string&gt; eventData = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEventDataMap();
  /**
   * <pre>
   * 事件的数据内容
   * </pre>
   *
   * <code>map&lt;string, string&gt; eventData = 5;</code>
   */
  /* nullable */
java.lang.String getEventDataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 事件的数据内容
   * </pre>
   *
   * <code>map&lt;string, string&gt; eventData = 5;</code>
   */
  java.lang.String getEventDataOrThrow(
      java.lang.String key);
}
