// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.aurora.grpc;

public interface EventAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.EventAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 响应码（200=成功）
   * </pre>
   *
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 响应消息
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 处理的事件数量
   * </pre>
   *
   * <code>int32 processedCount = 3;</code>
   * @return The processedCount.
   */
  int getProcessedCount();

  /**
   * <pre>
   * 失败的事件数量
   * </pre>
   *
   * <code>int32 failedCount = 4;</code>
   * @return The failedCount.
   */
  int getFailedCount();

  /**
   * <pre>
   * 处理时间戳
   * </pre>
   *
   * <code>int64 processedAt = 5;</code>
   * @return The processedAt.
   */
  long getProcessedAt();
}
