// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.aurora.grpc;

public final class EventServiceProto {
  private EventServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_BatchEventDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_BatchEventDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_EventDataMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_EventDataMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_EventDataMessage_EventDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_EventDataMessage_EventDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_EventAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_EventAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\006aurora\"A\n\025BatchEventDataR" +
      "equest\022(\n\006events\030\001 \003(\0132\030.aurora.EventDat" +
      "aMessage\"\311\001\n\020EventDataMessage\022\021\n\ttimesta" +
      "mp\030\001 \001(\003\022\021\n\teventType\030\002 \001(\r\022\017\n\007traceId\030\003" +
      " \001(\014\022\020\n\010sourceId\030\004 \001(\t\022:\n\teventData\030\005 \003(" +
      "\0132\'.aurora.EventDataMessage.EventDataEnt" +
      "ry\0320\n\016EventDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\"k\n\010EventAck\022\014\n\004code\030\001 \001(\005\022\017" +
      "\n\007message\030\002 \001(\t\022\026\n\016processedCount\030\003 \001(\005\022" +
      "\023\n\013failedCount\030\004 \001(\005\022\023\n\013processedAt\030\005 \001(" +
      "\0032\302\001\n\014EventService\0224\n\006Report\022\030.aurora.Ev" +
      "entDataMessage\032\020.aurora.EventAck\022<\n\014Repo" +
      "rtStream\022\030.aurora.EventDataMessage\032\020.aur" +
      "ora.EventAck(\001\022>\n\013ReportBatch\022\035.aurora.B" +
      "atchEventDataRequest\032\020.aurora.EventAckB7" +
      "\n\017com.aurora.grpcB\021EventServiceProtoP\001\252\002" +
      "\016EventData.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aurora_BatchEventDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aurora_BatchEventDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_BatchEventDataRequest_descriptor,
        new java.lang.String[] { "Events", });
    internal_static_aurora_EventDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aurora_EventDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_EventDataMessage_descriptor,
        new java.lang.String[] { "Timestamp", "EventType", "TraceId", "SourceId", "EventData", });
    internal_static_aurora_EventDataMessage_EventDataEntry_descriptor =
      internal_static_aurora_EventDataMessage_descriptor.getNestedTypes().get(0);
    internal_static_aurora_EventDataMessage_EventDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_EventDataMessage_EventDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_aurora_EventAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aurora_EventAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_EventAck_descriptor,
        new java.lang.String[] { "Code", "Message", "ProcessedCount", "FailedCount", "ProcessedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
