// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public final class MetricProto {
  private MetricProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_BatchMetricDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_BatchMetricDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricDataMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricDataMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricDataMessage_LabelsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricDataMessage_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricDataItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricDataItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aurora_MetricAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aurora_MetricAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014metric.proto\022\006aurora\"U\n\026BatchMetricDat" +
      "aRequest\022*\n\007metrics\030\001 \003(\0132\031.aurora.Metri" +
      "cDataMessage\022\017\n\007batchId\030\002 \001(\t\"\330\001\n\021Metric" +
      "DataMessage\022\021\n\ttimestamp\030\001 \001(\003\022\017\n\007traceI" +
      "d\030\002 \001(\014\022\020\n\010sourceId\030\003 \001(\t\022\'\n\007metrics\030\004 \003" +
      "(\0132\026.aurora.MetricDataItem\0225\n\006labels\030\005 \003" +
      "(\0132%.aurora.MetricDataMessage.LabelsEntr" +
      "y\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"S\n\016MetricDataItem\022\020\n\010metricId\030\001" +
      " \001(\005\022\r\n\005value\030\002 \001(\001\022\022\n\nmetricName\030\003 \001(\t\022" +
      "\014\n\004unit\030\004 \001(\t\"l\n\tMetricAck\022\014\n\004code\030\001 \001(\005" +
      "\022\017\n\007message\030\002 \001(\t\022\026\n\016processedCount\030\003 \001(" +
      "\005\022\023\n\013failedCount\030\004 \001(\005\022\023\n\013processedAt\030\005 " +
      "\001(\0032\311\001\n\rMetricService\0226\n\006Report\022\031.aurora" +
      ".MetricDataMessage\032\021.aurora.MetricAck\022>\n" +
      "\014ReportStream\022\031.aurora.MetricDataMessage" +
      "\032\021.aurora.MetricAck(\001\022@\n\013ReportBatch\022\036.a" +
      "urora.BatchMetricDataRequest\032\021.aurora.Me" +
      "tricAckB2\n\017com.aurora.grpcB\013MetricProtoP" +
      "\001\252\002\017MetricData.Grpcb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_aurora_BatchMetricDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aurora_BatchMetricDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_BatchMetricDataRequest_descriptor,
        new java.lang.String[] { "Metrics", "BatchId", });
    internal_static_aurora_MetricDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aurora_MetricDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricDataMessage_descriptor,
        new java.lang.String[] { "Timestamp", "TraceId", "SourceId", "Metrics", "Labels", });
    internal_static_aurora_MetricDataMessage_LabelsEntry_descriptor =
      internal_static_aurora_MetricDataMessage_descriptor.getNestedTypes().get(0);
    internal_static_aurora_MetricDataMessage_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricDataMessage_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_aurora_MetricDataItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aurora_MetricDataItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricDataItem_descriptor,
        new java.lang.String[] { "MetricId", "Value", "MetricName", "Unit", });
    internal_static_aurora_MetricAck_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aurora_MetricAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aurora_MetricAck_descriptor,
        new java.lang.String[] { "Code", "Message", "ProcessedCount", "FailedCount", "ProcessedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
