// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface MetricDataItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.MetricDataItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 指标类型ID
   * </pre>
   *
   * <code>int32 metricId = 1;</code>
   * @return The metricId.
   */
  int getMetricId();

  /**
   * <pre>
   * 指标值（简化为 double 类型）
   * </pre>
   *
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();
}
