// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface MetricDataItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.MetricDataItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 指标code
   * </pre>
   *
   * <code>string metricCode = 1;</code>
   * @return The metricCode.
   */
  java.lang.String getMetricCode();
  /**
   * <pre>
   * 指标code
   * </pre>
   *
   * <code>string metricCode = 1;</code>
   * @return The bytes for metricCode.
   */
  com.google.protobuf.ByteString
      getMetricCodeBytes();

  /**
   * <pre>
   * 指标值（简化为 double 类型）
   * </pre>
   *
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();
}
