// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface MetricDataMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.MetricDataMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 事件时间戳（Unix 毫秒时间戳）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 跟踪上下文（16字节的 trace ID）
   * </pre>
   *
   * <code>bytes traceId = 2;</code>
   * @return The traceId.
   */
  com.google.protobuf.ByteString getTraceId();

  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 3;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 3;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  java.util.List<com.aurora.grpc.MetricDataItem> 
      getMetricsList();
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  com.aurora.grpc.MetricDataItem getMetrics(int index);
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  int getMetricsCount();
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  java.util.List<? extends com.aurora.grpc.MetricDataItemOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  com.aurora.grpc.MetricDataItemOrBuilder getMetricsOrBuilder(
      int index);

  /**
   * <pre>
   * 通用标签信息 - 适用于本批次所有指标的共同属性
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 5;</code>
   */
  int getLabelsCount();
  /**
   * <pre>
   * 通用标签信息 - 适用于本批次所有指标的共同属性
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 5;</code>
   */
  boolean containsLabels(
      java.lang.String key);
  /**
   * Use {@link #getLabelsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getLabels();
  /**
   * <pre>
   * 通用标签信息 - 适用于本批次所有指标的共同属性
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getLabelsMap();
  /**
   * <pre>
   * 通用标签信息 - 适用于本批次所有指标的共同属性
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 5;</code>
   */
  /* nullable */
java.lang.String getLabelsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 通用标签信息 - 适用于本批次所有指标的共同属性
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 5;</code>
   */
  java.lang.String getLabelsOrThrow(
      java.lang.String key);
}
