// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

/**
 * <pre>
 * 指标消息 - 核心数据结构
 * </pre>
 *
 * Protobuf type {@code aurora.MetricDataMessage}
 */
public final class MetricDataMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:aurora.MetricDataMessage)
    MetricDataMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetricDataMessage.newBuilder() to construct.
  private MetricDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetricDataMessage() {
    traceId_ = com.google.protobuf.ByteString.EMPTY;
    sourceId_ = "";
    metrics_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetricDataMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aurora.grpc.MetricProto.internal_static_aurora_MetricDataMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aurora.grpc.MetricProto.internal_static_aurora_MetricDataMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aurora.grpc.MetricDataMessage.class, com.aurora.grpc.MetricDataMessage.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 事件时间戳（Unix 毫秒时间戳）
   * </pre>
   *
   * <code>int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int TRACEID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString traceId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * 跟踪上下文（16字节的 trace ID）
   * </pre>
   *
   * <code>bytes traceId = 2;</code>
   * @return The traceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTraceId() {
    return traceId_;
  }

  public static final int SOURCEID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceId_ = "";
  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 3;</code>
   * @return The sourceId.
   */
  @java.lang.Override
  public java.lang.String getSourceId() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 上报来源标识
   * </pre>
   *
   * <code>string sourceId = 3;</code>
   * @return The bytes for sourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceIdBytes() {
    java.lang.Object ref = sourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRICS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.aurora.grpc.MetricDataItem> metrics_;
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.aurora.grpc.MetricDataItem> getMetricsList() {
    return metrics_;
  }
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aurora.grpc.MetricDataItemOrBuilder> 
      getMetricsOrBuilderList() {
    return metrics_;
  }
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  @java.lang.Override
  public int getMetricsCount() {
    return metrics_.size();
  }
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  @java.lang.Override
  public com.aurora.grpc.MetricDataItem getMetrics(int index) {
    return metrics_.get(index);
  }
  /**
   * <pre>
   * 指标数据列表
   * </pre>
   *
   * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
   */
  @java.lang.Override
  public com.aurora.grpc.MetricDataItemOrBuilder getMetricsOrBuilder(
      int index) {
    return metrics_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeInt64(1, timestamp_);
    }
    if (!traceId_.isEmpty()) {
      output.writeBytes(2, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sourceId_);
    }
    for (int i = 0; i < metrics_.size(); i++) {
      output.writeMessage(4, metrics_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (!traceId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, traceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sourceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sourceId_);
    }
    for (int i = 0; i < metrics_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, metrics_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aurora.grpc.MetricDataMessage)) {
      return super.equals(obj);
    }
    com.aurora.grpc.MetricDataMessage other = (com.aurora.grpc.MetricDataMessage) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getTraceId()
        .equals(other.getTraceId())) return false;
    if (!getSourceId()
        .equals(other.getSourceId())) return false;
    if (!getMetricsList()
        .equals(other.getMetricsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + TRACEID_FIELD_NUMBER;
    hash = (53 * hash) + getTraceId().hashCode();
    hash = (37 * hash) + SOURCEID_FIELD_NUMBER;
    hash = (53 * hash) + getSourceId().hashCode();
    if (getMetricsCount() > 0) {
      hash = (37 * hash) + METRICS_FIELD_NUMBER;
      hash = (53 * hash) + getMetricsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aurora.grpc.MetricDataMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.aurora.grpc.MetricDataMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.aurora.grpc.MetricDataMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aurora.grpc.MetricDataMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aurora.grpc.MetricDataMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 指标消息 - 核心数据结构
   * </pre>
   *
   * Protobuf type {@code aurora.MetricDataMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:aurora.MetricDataMessage)
      com.aurora.grpc.MetricDataMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aurora.grpc.MetricProto.internal_static_aurora_MetricDataMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aurora.grpc.MetricProto.internal_static_aurora_MetricDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aurora.grpc.MetricDataMessage.class, com.aurora.grpc.MetricDataMessage.Builder.class);
    }

    // Construct using com.aurora.grpc.MetricDataMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      timestamp_ = 0L;
      traceId_ = com.google.protobuf.ByteString.EMPTY;
      sourceId_ = "";
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
      } else {
        metrics_ = null;
        metricsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aurora.grpc.MetricProto.internal_static_aurora_MetricDataMessage_descriptor;
    }

    @java.lang.Override
    public com.aurora.grpc.MetricDataMessage getDefaultInstanceForType() {
      return com.aurora.grpc.MetricDataMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.aurora.grpc.MetricDataMessage build() {
      com.aurora.grpc.MetricDataMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aurora.grpc.MetricDataMessage buildPartial() {
      com.aurora.grpc.MetricDataMessage result = new com.aurora.grpc.MetricDataMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aurora.grpc.MetricDataMessage result) {
      if (metricsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          metrics_ = java.util.Collections.unmodifiableList(metrics_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.metrics_ = metrics_;
      } else {
        result.metrics_ = metricsBuilder_.build();
      }
    }

    private void buildPartial0(com.aurora.grpc.MetricDataMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.traceId_ = traceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sourceId_ = sourceId_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aurora.grpc.MetricDataMessage) {
        return mergeFrom((com.aurora.grpc.MetricDataMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aurora.grpc.MetricDataMessage other) {
      if (other == com.aurora.grpc.MetricDataMessage.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getTraceId() != com.google.protobuf.ByteString.EMPTY) {
        setTraceId(other.getTraceId());
      }
      if (!other.getSourceId().isEmpty()) {
        sourceId_ = other.sourceId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (metricsBuilder_ == null) {
        if (!other.metrics_.isEmpty()) {
          if (metrics_.isEmpty()) {
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMetricsIsMutable();
            metrics_.addAll(other.metrics_);
          }
          onChanged();
        }
      } else {
        if (!other.metrics_.isEmpty()) {
          if (metricsBuilder_.isEmpty()) {
            metricsBuilder_.dispose();
            metricsBuilder_ = null;
            metrics_ = other.metrics_;
            bitField0_ = (bitField0_ & ~0x00000008);
            metricsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetricsFieldBuilder() : null;
          } else {
            metricsBuilder_.addAllMessages(other.metrics_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              traceId_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              sourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.aurora.grpc.MetricDataItem m =
                  input.readMessage(
                      com.aurora.grpc.MetricDataItem.parser(),
                      extensionRegistry);
              if (metricsBuilder_ == null) {
                ensureMetricsIsMutable();
                metrics_.add(m);
              } else {
                metricsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long timestamp_ ;
    /**
     * <pre>
     * 事件时间戳（Unix 毫秒时间戳）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 事件时间戳（Unix 毫秒时间戳）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件时间戳（Unix 毫秒时间戳）
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString traceId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 跟踪上下文（16字节的 trace ID）
     * </pre>
     *
     * <code>bytes traceId = 2;</code>
     * @return The traceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTraceId() {
      return traceId_;
    }
    /**
     * <pre>
     * 跟踪上下文（16字节的 trace ID）
     * </pre>
     *
     * <code>bytes traceId = 2;</code>
     * @param value The traceId to set.
     * @return This builder for chaining.
     */
    public Builder setTraceId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      traceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 跟踪上下文（16字节的 trace ID）
     * </pre>
     *
     * <code>bytes traceId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTraceId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      traceId_ = getDefaultInstance().getTraceId();
      onChanged();
      return this;
    }

    private java.lang.Object sourceId_ = "";
    /**
     * <pre>
     * 上报来源标识
     * </pre>
     *
     * <code>string sourceId = 3;</code>
     * @return The sourceId.
     */
    public java.lang.String getSourceId() {
      java.lang.Object ref = sourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 上报来源标识
     * </pre>
     *
     * <code>string sourceId = 3;</code>
     * @return The bytes for sourceId.
     */
    public com.google.protobuf.ByteString
        getSourceIdBytes() {
      java.lang.Object ref = sourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 上报来源标识
     * </pre>
     *
     * <code>string sourceId = 3;</code>
     * @param value The sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sourceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上报来源标识
     * </pre>
     *
     * <code>string sourceId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceId() {
      sourceId_ = getDefaultInstance().getSourceId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 上报来源标识
     * </pre>
     *
     * <code>string sourceId = 3;</code>
     * @param value The bytes for sourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sourceId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.aurora.grpc.MetricDataItem> metrics_ =
      java.util.Collections.emptyList();
    private void ensureMetricsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        metrics_ = new java.util.ArrayList<com.aurora.grpc.MetricDataItem>(metrics_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aurora.grpc.MetricDataItem, com.aurora.grpc.MetricDataItem.Builder, com.aurora.grpc.MetricDataItemOrBuilder> metricsBuilder_;

    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public java.util.List<com.aurora.grpc.MetricDataItem> getMetricsList() {
      if (metricsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metrics_);
      } else {
        return metricsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public int getMetricsCount() {
      if (metricsBuilder_ == null) {
        return metrics_.size();
      } else {
        return metricsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public com.aurora.grpc.MetricDataItem getMetrics(int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);
      } else {
        return metricsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder setMetrics(
        int index, com.aurora.grpc.MetricDataItem value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.set(index, value);
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder setMetrics(
        int index, com.aurora.grpc.MetricDataItem.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder addMetrics(com.aurora.grpc.MetricDataItem value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder addMetrics(
        int index, com.aurora.grpc.MetricDataItem value) {
      if (metricsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricsIsMutable();
        metrics_.add(index, value);
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder addMetrics(
        com.aurora.grpc.MetricDataItem.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder addMetrics(
        int index, com.aurora.grpc.MetricDataItem.Builder builderForValue) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder addAllMetrics(
        java.lang.Iterable<? extends com.aurora.grpc.MetricDataItem> values) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metrics_);
        onChanged();
      } else {
        metricsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder clearMetrics() {
      if (metricsBuilder_ == null) {
        metrics_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        metricsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public Builder removeMetrics(int index) {
      if (metricsBuilder_ == null) {
        ensureMetricsIsMutable();
        metrics_.remove(index);
        onChanged();
      } else {
        metricsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public com.aurora.grpc.MetricDataItem.Builder getMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public com.aurora.grpc.MetricDataItemOrBuilder getMetricsOrBuilder(
        int index) {
      if (metricsBuilder_ == null) {
        return metrics_.get(index);  } else {
        return metricsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public java.util.List<? extends com.aurora.grpc.MetricDataItemOrBuilder> 
         getMetricsOrBuilderList() {
      if (metricsBuilder_ != null) {
        return metricsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metrics_);
      }
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public com.aurora.grpc.MetricDataItem.Builder addMetricsBuilder() {
      return getMetricsFieldBuilder().addBuilder(
          com.aurora.grpc.MetricDataItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public com.aurora.grpc.MetricDataItem.Builder addMetricsBuilder(
        int index) {
      return getMetricsFieldBuilder().addBuilder(
          index, com.aurora.grpc.MetricDataItem.getDefaultInstance());
    }
    /**
     * <pre>
     * 指标数据列表
     * </pre>
     *
     * <code>repeated .aurora.MetricDataItem metrics = 4;</code>
     */
    public java.util.List<com.aurora.grpc.MetricDataItem.Builder> 
         getMetricsBuilderList() {
      return getMetricsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aurora.grpc.MetricDataItem, com.aurora.grpc.MetricDataItem.Builder, com.aurora.grpc.MetricDataItemOrBuilder> 
        getMetricsFieldBuilder() {
      if (metricsBuilder_ == null) {
        metricsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aurora.grpc.MetricDataItem, com.aurora.grpc.MetricDataItem.Builder, com.aurora.grpc.MetricDataItemOrBuilder>(
                metrics_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        metrics_ = null;
      }
      return metricsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:aurora.MetricDataMessage)
  }

  // @@protoc_insertion_point(class_scope:aurora.MetricDataMessage)
  private static final com.aurora.grpc.MetricDataMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aurora.grpc.MetricDataMessage();
  }

  public static com.aurora.grpc.MetricDataMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetricDataMessage>
      PARSER = new com.google.protobuf.AbstractParser<MetricDataMessage>() {
    @java.lang.Override
    public MetricDataMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetricDataMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetricDataMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aurora.grpc.MetricDataMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

