// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

package com.aurora.grpc;

public interface TelemetryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.TelemetryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 指标名
   * </pre>
   *
   * <code>string metric = 1;</code>
   * @return The metric.
   */
  java.lang.String getMetric();
  /**
   * <pre>
   * 指标名
   * </pre>
   *
   * <code>string metric = 1;</code>
   * @return The bytes for metric.
   */
  com.google.protobuf.ByteString
      getMetricBytes();

  /**
   * <pre>
   * 指标值
   * </pre>
   *
   * <code>double value = 2;</code>
   * @return The value.
   */
  double getValue();

  /**
   * <pre>
   * Unix毫秒时间戳
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 标签
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   * 标签
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  boolean containsTags(
      java.lang.String key);
  /**
   * Use {@link #getTagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTags();
  /**
   * <pre>
   * 标签
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTagsMap();
  /**
   * <pre>
   * 标签
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  /* nullable */
java.lang.String getTagsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 标签
   * </pre>
   *
   * <code>map&lt;string, string&gt; tags = 4;</code>
   */
  java.lang.String getTagsOrThrow(
      java.lang.String key);
}
