spring:
  kafka:
    bootstrap-servers: 118.25.129.41:9092
    consumer:
      group-id: common-consumer
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 1000  # 单次拉取的最大条数
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer



# 自定义kafka配置
kafka:
  custom:
    # kafka认证开关
    auth-switch: false
    # SASL mechanism配置
    sasl-mechanism: SCRAM-SHA-256
    # 授权信息
    sasl-jaas-config: org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"adminpwd\";
    # 消费线程池大小
    consumer-thread-pool-size: 10
    # 指标topic
    metric-topic: metric



clickhouse:
  url: http://118.25.129.41:8123/
  username: test
  password: 123456
  database: test_db
  socket-timeout: 30000
  connection-timeout: 5000

