// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface BatchMetricRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.BatchMetricRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .aurora.MetricMessage metrics = 1;</code>
   */
  java.util.List<com.aurora.grpc.MetricMessage> 
      getMetricsList();
  /**
   * <code>repeated .aurora.MetricMessage metrics = 1;</code>
   */
  com.aurora.grpc.MetricMessage getMetrics(int index);
  /**
   * <code>repeated .aurora.MetricMessage metrics = 1;</code>
   */
  int getMetricsCount();
  /**
   * <code>repeated .aurora.MetricMessage metrics = 1;</code>
   */
  java.util.List<? extends com.aurora.grpc.MetricMessageOrBuilder> 
      getMetricsOrBuilderList();
  /**
   * <code>repeated .aurora.MetricMessage metrics = 1;</code>
   */
  com.aurora.grpc.MetricMessageOrBuilder getMetricsOrBuilder(
      int index);
}
