// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric.proto

package com.aurora.grpc;

public interface MetricMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aurora.MetricMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 placeId = 1;</code>
   * @return The placeId.
   */
  int getPlaceId();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int64 time = 3;</code>
   * @return The time.
   */
  long getTime();

  /**
   * <code>int32 pid = 4;</code>
   * @return The pid.
   */
  int getPid();

  /**
   * <code>repeated .aurora.MetricItem metrics = 5;</code>
   */
  java.util.List<MetricItem>
      getMetricsList();
  /**
   * <code>repeated .aurora.MetricItem metrics = 5;</code>
   */
  MetricItem getMetrics(int index);
  /**
   * <code>repeated .aurora.MetricItem metrics = 5;</code>
   */
  int getMetricsCount();
  /**
   * <code>repeated .aurora.MetricItem metrics = 5;</code>
   */
  java.util.List<? extends MetricItemOrBuilder>
      getMetricsOrBuilderList();
  /**
   * <code>repeated .aurora.MetricItem metrics = 5;</code>
   */
  MetricItemOrBuilder getMetricsOrBuilder(
      int index);
}
